### ISSUE TITLE
Zero's submash, variation mask on default must be 1, but don't 0

### ISSUE THREAD

**Issue by AngelHeavenly** [Acc3ssViolation/ExtendedAssetEditor#4]
In your mod generated name for trailer variation and in option set in the zero submesh, m_variationMask have zero. Vanilla asset set this by default is one. 

A fix is ​​required as the workaround is redundant: This increases the size of the asset. 
This causes the game to not correctly use the lighting textures in the lod.

Please fix it.

**Comment by Acc3ssViolation** [comment]
Right, it appears that the freight train wagon has the mask set to 1 for the `m_subMeshes[0]` so that the main mesh is hidden when any of the other variations are used. The regular passenger train assets or the freight train locomotive do not use other submeshes, their mask is set to 0 for the main mesh.

So I'm guessing the issue here is that the main mesh will never be hidden for custom assets, correct? I guess it can be fixed by adding an extra field in the UI for the main mesh mask.

**Comment by Acc3ssViolation** [comment]
Extra field added in version 0.7.2 to edit the main mesh variation mask:
![image](https://user-images.githubusercontent.com/20259787/233449445-7bdf9078-516e-4bf0-86de-9ac513d6bcd5.png)

**Comment by AngelHeavenly** [comment]
No, it don't fix it. See it in my screens. Before set m_variationMask:
![image](https://user-images.githubusercontent.com/71866284/233613488-ef109f46-c68a-4db5-afad-6030a0b6bc65.png)
After: 
![image](https://user-images.githubusercontent.com/71866284/233613676-2b2a087d-4bed-4053-9bc8-2f918721df9e.png)

i'm use only your mod in create this trailers and train.

**Comment by AngelHeavenly** [comment]
If you want see my asset: [RZD_VL80-fix_d.zip](https://github.com/Acc3ssViolation/ExtendedAssetEditor/files/11294905/RZD_VL80-fix_d.zip)

**Comment by Acc3ssViolation** [comment]
Thanks, turns out the variation mask for the main mesh just isn't saved at all, I hadn't noticed. It'll require a change to TrailerVariationLoader mod as well.

Main mod is updated to 0.7.3 which saves it in a way the updated Trailer Variation Loader can load.

With that done the train does seem to work now:

![image](https://user-images.githubusercontent.com/20259787/233711630-4a50f32f-8ac1-4535-8c97-84abbba6fc7e.png)
![image](https://user-images.githubusercontent.com/20259787/233711684-fca993db-4adb-4d12-857c-0759cb41216c.png)
[RZD_VL80_SubmeshFix.zip](https://github.com/Acc3ssViolation/ExtendedAssetEditor/files/11298463/RZD_VL80_SubmeshFix.zip)

**Comment by AngelHeavenly** [comment]
YES! It fixed! Thanks!
![image](https://user-images.githubusercontent.com/71866284/233749177-55592ef1-7084-4a9e-82f0-b1a8361949f9.png)

It remains to add a preview through your mod and everything else for decoration.

**Comment by AngelHeavenly** [comment]
![image](https://user-images.githubusercontent.com/71866284/236436648-a5a3c254-cfa3-4de3-ad26-bbcb26512949.png)
![image](https://user-images.githubusercontent.com/71866284/236440401-fc22503c-b062-44b1-994b-d507118e1b27.png)
[output_log — копия.txt](https://github.com/Acc3ssViolation/ExtendedAssetEditor/files/11405528/output_log.txt)

[output_log.txt](https://github.com/Acc3ssViolation/ExtendedAssetEditor/files/11405537/output_log.txt)
